import { ArrowUpRight, CheckCircle2, PackageCheck, ShieldCheck, Truck, WalletCards } from "lucide-react";
import SiteLayout, { PageHero, SectionHead } from "@/components/SiteLayout";

const steps = [
  { number: "01", icon: WalletCards, title: "Invoice Issuance", english: "Invoice Issuance", body: "We issue a Proforma Invoice based on the confirmed product, specification, quantity, and delivery requirements. Payment methods include PayPal and USDT.", image: "/W/assets/paypal-invoice_773e2a32.png", alt: "Proforma invoice and PayPal payment" },
  { number: "02", icon: ShieldCheck, title: "Payment Confirmation", english: "Payment Confirmation", body: "After payment, send us a screenshot of the successful transaction so our finance and order teams can verify it and proceed.", image: "/W/assets/peptide-factory_e4e70e6a.jpg", alt: "Peptide manufacturing facility" },
  { number: "03", icon: PackageCheck, title: "Processing & Dispatch", english: "Processing & Dispatch", body: "After payment confirmation, the warehouse team prepares the products, verifies batch documentation, and completes packaging for dispatch.", image: "/W/assets/pharma-warehouse_4a30eb5c.jpg", alt: "Pharmaceutical warehouse and order preparation" },
  { number: "04", icon: Truck, title: "Shipment Tracking & Delivery", english: "Shipment Tracking & Delivery", body: "After dispatch, we provide the shipment tracking number and actual photographs of the packaged products, then continue follow-up until delivery.", image: "/W/assets/logistics-packaging_c240ecdc.jpg", alt: "Pharmaceutical logistics and packaging" },
];

export default function Order() {
  return <SiteLayout><main>
    <PageHero index="08" kicker="ORDER & SHIPPING" title={<>Every order,<br /><em>has a clear delivery path.</em></>} intro="From Proforma Invoice and payment confirmation to packaging, tracking, and final delivery, Tide makes every order milestone clear." />
    <section className="section order-intro-section"><div className="container order-intro"><div><span className="archive-label">SECURE ORDERING / Secure Ordering</span><h2>Before payment,<br /><em>we make the process clear.</em></h2></div><div><p className="order-lead">We support PayPal or cryptocurrency (USDT). Every order follows the product, specification, quantity, packaging, and delivery conditions confirmed by both parties.</p><p>After payment, please send a screenshot of the successful transaction so we can verify the order status. After dispatch, we provide the shipment tracking number and photographs of the completed packaging.</p><div className="order-payment-note"><strong>PAYMENT METHODS</strong><span>PayPal · USDT</span></div></div></div></section>
    <section className="section order-steps-section"><div className="container"><SectionHead index="08A" kicker="ORDER FLOW / Order Flow" title={<>Four steps,<br /><em>from payment to receiving the shipment.</em></>} intro="Each step has clear documentation, actions, and communication points." /><div className="order-steps-grid">{steps.map(({ number, icon: Icon, title, english, body, image, alt }) => <article className="order-step-card" key={number}><div className="order-step-image"><img src={image} alt={alt} /></div><div className="order-step-content"><div className="order-step-top"><Icon size={18} /><span>{number}</span></div><small>{english}</small><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
    <section className="section order-guarantees-section"><div className="container"><div className="order-guarantees-head"><span className="archive-label">OUR GUARANTEES / OUR GUARANTEES</span><h2>Delivery responsibility<br /><em>at every milestone.</em></h2></div><div className="order-guarantees-grid"><article><span>01</span><CheckCircle2 /><h3>Delivery Guarantee</h3><p>If a package encounters an issue during customs clearance, we will discuss a refund or reshipment arrangement based on the order and continue following up on the delivery result.</p></article><article><span>02</span><CheckCircle2 /><h3>long-term collaboration</h3><p>We value stable supply relationships. Clear product documentation, batch communication, and delivery follow-up create a repeatable workflow for long-term collaboration.</p></article><article><span>03</span><CheckCircle2 /><h3>Guangzhou Factory Visit</h3><p>If you visit China, we welcome you to schedule a visit to our Guangzhou facility and see the product R&D, production environment, and quality management process.</p></article></div></div></section>
    <section className="section order-cta-section"><div className="container order-cta"><div><span className="archive-label">READY TO ORDER</span><h2>Send us the product model,<br /><em>begin with a clear message.</em></h2></div><div><p>Send the product model, specification, quantity, and target market through WhatsApp. We will respond with the relevant product documentation and order flow.</p><a className="button button-dark" href="https://wa.me/85253929189" target="_blank" rel="noreferrer">WhatsApp Quote & Order <ArrowUpRight size={16} /></a></div></div></section>
  </main></SiteLayout>;
}
